import fs from 'node:fs';
import path from 'node:path';
import {
  compileProviderBlocks, stripRuleMarkers, replacePlaceholders, escapeGoTemplate,
  sliceSection, tomlString, parseFrontmatter,
} from './text.mjs';

const TEMPLATES = path.join(path.dirname(new URL(import.meta.url).pathname), '..', 'templates');

function write(file, content, mode) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
  if (mode) fs.chmodSync(file, mode);
}

function copyTree(src, dst) {
  fs.mkdirSync(dst, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dst, entry.name);
    if (entry.isDirectory()) copyTree(s, d);
    else fs.copyFileSync(s, d);
    if (!entry.isDirectory()) fs.chmodSync(d, fs.statSync(s).mode);
  }
}

function titleCase(dirName) {
  return dirName.split('-').map((w) => w[0].toUpperCase() + w.slice(1)).join(' ');
}

// Impeccable prose -> text safe to place inside a Gas City prompt template.
export function compileProse(markdown, placeholders) {
  return escapeGoTemplate(replacePlaceholders(stripRuleMarkers(compileProviderBlocks(markdown)), placeholders));
}

export function agentToml(agent, packName, { installPath, apiUrl }) {
  const opts = [];
  if (agent.effort) opts.push(`effort = ${tomlString(agent.effort)}`);
  if (agent.model) opts.push(`model = ${tomlString(agent.model)}`);
  const lines = [
    `# Generated by gascity/convert from ${agent.origin}. Do not edit by hand.`,
    `#`,
    `# Impeccable tools: ${agent.tools.join(', ') || '(none listed)'}`,
    `# Everything a Claude Code session offers beyond that list is launched`,
    `# disallowed, so the advisory list upstream is enforced here.`,
    agent.maxTurns ? `# Upstream max-turns: ${agent.maxTurns} (Gas City bounds a step by its timeout instead).` : null,
    `description = ${tomlString(agent.description)}`,
    `scope = "rig"`,
    opts.length ? `option_defaults = { ${opts.join(', ')} }` : `# option_defaults: inherits the provider's model and effort`,
    `args = [${['--disallowedTools', agent.disallowedTools.join(',')].map(tomlString).join(', ')}]`,
    ``,
    `# Labels this agent's Claude Code telemetry so tokens and cost can be read`,
    `# back per agent (gc derives gc.agent from an environment that, under the`,
    `# supervisor, names no agent).`,
    `[env]`,
    `OTEL_RESOURCE_ATTRIBUTES = ${tomlString(`gc.agent=${packName}.${agent.dirName}`)}`,
    `# Where this pack is installed and where step.sh reads and writes beads.`,
    `# Baked in at conversion time (--install-path, --api-url) so the city's`,
    `# own config needs no edit. city.toml.example shows the [workspace.env] form.`,
    `IMPECCABLE_PACK = ${tomlString(installPath)}`,
    `IMPECCABLE_API = ${tomlString(apiUrl)}`,
    ``,
  ].filter((l) => l !== null);
  return lines.join('\n');
}

// Prompt for an agent that exists upstream as skill/agents/*.md.
export function convertedAgentPrompt(agent, placeholders) {
  const body = compileProse(agent.body, placeholders);
  return `# ${titleCase(agent.dirName)}

You are \`{{ .AgentName }}\`; your session is \`$GC_SESSION_ID\`. You are
Impeccable's \`${agent.sourceName}\` sub-agent, running as a Gas City agent. In
Impeccable's native form a parent context spawns you with a packet in the
prompt and reads your single return message. Here the packet is the step
routed to you, and your return message is a file.

{{ template "impeccable-common" . }}

## How your work arrives and leaves

- The step description is the packet the parent would have written. Paths it
  names are relative to the rig repository unless written absolute.
- Anything the definition below says to "return" goes in a file: write it with
  \`step.sh result "$STEP" result.md\`, keeping the exact output contract the
  definition asks for. Then close the step with a one-line summary.
- If the definition says to stop and ask, write the question into
  \`result.md\` and close the step with \`fail\` and the reason; a later step or
  a person decides what happens next.

## Impeccable's definition of this agent

${body.trim()}
`;
}

// Prompt for a role lifted out of critique.md (conductor, assessors).
export function syntheticAgentPrompt(agent, critiqueMd, placeholders) {
  const template = fs.readFileSync(path.join(TEMPLATES, 'agents', agent.template), 'utf8');
  const sections = {
    SETUP: sliceSection(critiqueMd, '### Setup'),
    ASSESSMENT_A: sliceSection(critiqueMd, '### Assessment A: Design Review'),
    ASSESSMENT_B: sliceSection(critiqueMd, '### Assessment B: Detector + Browser Evidence'),
    REPORT: sliceSection(critiqueMd, '### Generate Combined Critique Report', '### Deliver the Report'),
    PERSIST: sliceSection(critiqueMd, '### Persist the Snapshot').replace(/^### Persist the Snapshot\n/, ''),
    ASK: sliceSection(critiqueMd, '### Ask the User', '### Recommended Actions').replace(/^### Ask the User\n/, ''),
    REFERENCE_MATERIAL: sliceSection(critiqueMd, '## Reference Material'),
  };
  // The template itself carries Go directives ({{ .AgentName }}, {{ template }}),
  // so only the lifted sections go through the escaping compiler.
  const filled = template.replace(/@@SECTION:([A-Z_]+)@@/g, (_, key) => {
    if (!(key in sections)) throw new Error(`unknown section marker ${key} in ${agent.template}`);
    return compileProse(sections[key], placeholders).trim();
  });
  return replacePlaceholders(filled, placeholders);
}

export function packToml(packName, agents, sourceVersion) {
  const sessions = agents.map((a) => `[[named_session]]
template = ${tomlString(a.dirName)}
scope = "rig"
mode = "on_demand"`).join('\n\n');
  return `# The Impeccable pack: pbakaus/impeccable's Claude Code sub-agent system as
# Gas City agents and formulas.
#
# Generated by gascity/convert from Impeccable ${sourceVersion}. Do not edit by
# hand; rerun the converter.
#
# Installed on a rig with:
#
#   gc rig add /path/to/project --name <name> --include /path/to/this/pack
#
# which stamps every agent below as <name>/${packName}.<agent>. The workflows are
# in formulas/; each step names the agent that runs it through gc.run_target.
#
# Each agents/<name>/prompt.template.md is picked up by convention. Do not set
# prompt_template in an agent.toml: an explicit value resolves against the pack
# root, not the agent's directory.
#
# Requires in city.toml [workspace.env]:
#   IMPECCABLE_PACK = "<absolute path of this pack>"
#   IMPECCABLE_API  = "http://127.0.0.1:8372/v0/city/<city>"
# See city.toml.example next to this file.
[pack]
name = ${tomlString(packName)}
schema = 2
description = "Impeccable design skill as isolated Gas City agents: critique assessors, synthesizer, finish reviewer, asset producer, documenter, manual-edit applier."

# on_demand: a session is started when a step is routed to the agent and is
# reclaimed when it goes idle. Every prompt tells its agent to re-read the
# workflow directory before acting; the files are the memory.
${sessions}
`;
}

export function cityTomlExample(packName, installPath, apiUrl) {
  return `# Add to the city's city.toml. The API URL is the machine-wide supervisor's
# listener with the city name appended; it is the same host and port the
# factory pack's FACTORY_API uses on the reference deployment.
[workspace.env]
IMPECCABLE_PACK = ${tomlString(installPath)}
IMPECCABLE_API = ${tomlString(apiUrl)}

# Then, per project:
#   gc rig add /opt/gascity/projects/<name> --name <name> --include ${installPath}
#   gc sling <name>/${packName}.conductor critique --formula --var target=index.html
`;
}

export function emitPack({ out, packName, source, agents, sourceVersion, placeholders, installPath, apiUrl }) {
  fs.rmSync(out, { recursive: true, force: true });
  const critiqueMd = fs.readFileSync(path.join(source, 'skill', 'reference', 'critique.md'), 'utf8');

  write(path.join(out, 'pack.toml'), packToml(packName, agents, sourceVersion));
  write(path.join(out, 'city.toml.example'), cityTomlExample(packName, installPath, apiUrl));

  for (const agent of agents) {
    const dir = path.join(out, 'agents', agent.dirName);
    write(path.join(dir, 'agent.toml'), agentToml(agent, packName, { installPath, apiUrl }));
    const prompt = agent.template
      ? syntheticAgentPrompt(agent, critiqueMd, placeholders)
      : convertedAgentPrompt(agent, placeholders);
    write(path.join(dir, 'prompt.template.md'), prompt);
  }

  write(
    path.join(out, 'template-fragments', 'impeccable-common.template.md'),
    fs.readFileSync(path.join(TEMPLATES, 'impeccable-common.template.md'), 'utf8'),
  );

  for (const f of fs.readdirSync(path.join(TEMPLATES, 'formulas'))) {
    const body = fs.readFileSync(path.join(TEMPLATES, 'formulas', f), 'utf8')
      .replace(/@@PACK@@/g, packName)
      .replace(/@@SOURCE_VERSION@@/g, sourceVersion);
    write(path.join(out, 'formulas', f), body);
  }

  for (const f of fs.readdirSync(path.join(TEMPLATES, 'scripts'))) {
    write(path.join(out, 'scripts', f), fs.readFileSync(path.join(TEMPLATES, 'scripts', f), 'utf8'), 0o755);
  }

  // The skill itself, compiled for this target, so agents can read the
  // command references and run the engine from inside the pack.
  const skillSrc = path.join(source, 'skill');
  const { data, body } = parseFrontmatter(fs.readFileSync(path.join(skillSrc, 'SKILL.src.md'), 'utf8'));
  const skillBody = replacePlaceholders(stripRuleMarkers(compileProviderBlocks(body)), placeholders);
  write(path.join(out, 'skill', 'SKILL.md'), `---\nname: ${data.name}\ndescription: ${JSON.stringify(data.description)}\n---\n${skillBody}`);
  for (const f of fs.readdirSync(path.join(skillSrc, 'reference'))) {
    const ref = fs.readFileSync(path.join(skillSrc, 'reference', f), 'utf8');
    write(path.join(out, 'skill', 'reference', f), replacePlaceholders(stripRuleMarkers(compileProviderBlocks(ref)), placeholders));
  }
  copyTree(path.join(skillSrc, 'scripts'), path.join(out, 'skill', 'scripts'));
  for (const f of ['LICENSE', 'NOTICE.md']) {
    const p = path.join(source, f);
    if (fs.existsSync(p)) fs.copyFileSync(p, path.join(out, 'skill', f));
  }

  const manifest = {
    generator: 'gascity/convert/impeccable-to-gascity.mjs',
    generatedAt: new Date().toISOString(),
    source: sourceVersion,
    pack: packName,
    agents: agents.map((a) => ({
      name: `${packName}.${a.dirName}`,
      origin: a.origin,
      tools: a.tools,
      disallowedTools: a.disallowedTools,
      readOnly: a.readOnly,
      effort: a.effort,
      model: a.model || 'inherit',
      maxTurns: a.maxTurns,
    })),
    formulas: fs.readdirSync(path.join(out, 'formulas')).map((f) => f.replace(/\.toml$/, '')),
  };
  write(path.join(out, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  return manifest;
}

// The baseline arm for the comparison: one unrestricted Claude Code session
// with Impeccable's own Claude build installed in the rig, so the skill spawns
// its sub-agents through the Task tool exactly as it does on a laptop.
export function emitBaselinePack({ out, packName, sourceVersion, installPath, apiUrl }) {
  fs.rmSync(out, { recursive: true, force: true });
  const base = path.join(TEMPLATES, 'baseline');
  for (const rel of ['pack.toml', 'agents/runner/agent.toml', 'agents/runner/prompt.template.md', 'formulas/critique-native.toml', 'formulas/build-native.toml']) {
    const body = fs.readFileSync(path.join(base, rel), 'utf8')
      .replace(/@@PACK@@/g, packName)
      .replace(/@@SOURCE_VERSION@@/g, sourceVersion)
      .replace(/@@INSTALL_PATH@@/g, installPath)
      .replace(/@@API_URL@@/g, apiUrl);
    write(path.join(out, rel), body);
  }
  write(path.join(out, 'scripts', 'step.sh'), fs.readFileSync(path.join(TEMPLATES, 'scripts', 'step.sh'), 'utf8'), 0o755);
}
